name: esb
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - xlrd
  - jupyter
  - jupyter_contrib_nbextensions
  - tqdm
  - scikit-learn
  - pytorch::pytorch=1.10
  - cudatoolkit=10.2
  - tslearn
  - optuna
  - dash=2.0.0
  - pyfmi
  - pip
  - pip:
    - python-dateutil
    - ipyvolume
    - gym
    - tensorboard
    - tensorboardX
    - higher==0.2.1
    - git+https://git.isis.vanderbilt.edu/SmartBuildings/bdx.git@v0.2.6
    - git+https://github.com/CPCLAB-UNIPI/SIPPY@6c233881f32280ee79267cba06b2f56984424ebd#egg=sippy