name: esb-prod
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - xlrd
  - tqdm
  - scikit-learn
  - dash=1.17.0
  - pip
  - pip:
    - python-dateutil
    - gym
    - git+https://git.isis.vanderbilt.edu/SmartBuildings/bdx.git@v0.2.5