name: esb-prod
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - scipy
  - pytorch::cpuonly
  - pytorch::pytorch=1.10
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - dash=1.17.0
  - ffmpeg
  - pip
  - pip:
    - higher
    - gym
    - tensorboard
    - python-dateutil
    - git+https://git.isis.vanderbilt.edu/SmartBuildings/bdx.git@v0.2.6