name: esb
channels:
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pandas
  - matplotlib
  - xlrd
  - jupyter
  - tqdm
  - scikit-learn
  - pip
  - pip:
    - dateutil
    - ipyvolume
    - gym
    - git+https://git.isis.vanderbilt.edu/SmartBuildings/bdx@v0.2.2