title: Engineering Science Building
description: Smart control of HVAC systems using data-driven methods.
show_downloads: true
theme: minima

header_pages:
  - index.md

github_username: hazrmard/EngineeringScienceBuilding